DROP POLICY IF EXISTS tenant_scope ON bauer_rag_v4.tenants;
DROP POLICY IF EXISTS tenant_admin_scope ON bauer_rag_v4.tenants;
DROP POLICY IF EXISTS kb_scope ON bauer_rag_v4.knowledge_bases;
DROP POLICY IF EXISTS kb_admin_scope ON bauer_rag_v4.knowledge_bases;
DROP POLICY IF EXISTS principal_admin_scope ON bauer_rag_v4.principals;
DROP POLICY IF EXISTS grants_admin_scope ON bauer_rag_v4.principal_source_grants;
DROP POLICY IF EXISTS source_read_scope ON bauer_rag_v4.source_documents;
DROP POLICY IF EXISTS source_worker_scope ON bauer_rag_v4.source_documents;
DROP POLICY IF EXISTS source_admin_scope ON bauer_rag_v4.source_documents;
DROP POLICY IF EXISTS version_read_scope ON bauer_rag_v4.source_versions;
DROP POLICY IF EXISTS version_worker_scope ON bauer_rag_v4.source_versions;
DROP POLICY IF EXISTS release_pinned_scope ON bauer_rag_v4.knowledge_releases;
DROP POLICY IF EXISTS release_reviewer_scope ON bauer_rag_v4.knowledge_releases;
DROP POLICY IF EXISTS release_admin_scope ON bauer_rag_v4.knowledge_releases;
DROP POLICY IF EXISTS release_source_read_scope ON bauer_rag_v4.release_sources;
DROP POLICY IF EXISTS release_source_worker_scope ON bauer_rag_v4.release_sources;
DROP POLICY IF EXISTS active_pointer_admin_scope ON bauer_rag_v4.active_release_pointers;
DROP POLICY IF EXISTS canonical_document_read_scope ON bauer_rag_v4.canonical_documents;
DROP POLICY IF EXISTS canonical_document_worker_scope ON bauer_rag_v4.canonical_documents;
DROP POLICY IF EXISTS canonical_blocks_read_scope ON bauer_rag_v4.canonical_blocks;
DROP POLICY IF EXISTS canonical_blocks_worker_scope ON bauer_rag_v4.canonical_blocks;
DROP POLICY IF EXISTS canonical_tables_read_scope ON bauer_rag_v4.canonical_tables;
DROP POLICY IF EXISTS canonical_tables_worker_scope ON bauer_rag_v4.canonical_tables;
DROP POLICY IF EXISTS canonical_cells_read_scope ON bauer_rag_v4.canonical_cells;
DROP POLICY IF EXISTS canonical_cells_worker_scope ON bauer_rag_v4.canonical_cells;
DROP POLICY IF EXISTS canonical_facts_read_scope ON bauer_rag_v4.canonical_facts;
DROP POLICY IF EXISTS canonical_facts_worker_scope ON bauer_rag_v4.canonical_facts;
DROP POLICY IF EXISTS search_projections_read_scope ON bauer_rag_v4.search_projections;
DROP POLICY IF EXISTS search_projections_worker_scope ON bauer_rag_v4.search_projections;
DROP POLICY IF EXISTS embedding_cache_worker_scope ON bauer_rag_v4.embedding_cache;
DROP POLICY IF EXISTS job_worker_scope ON bauer_rag_v4.compilation_jobs;
DROP POLICY IF EXISTS audit_admin_scope ON bauer_rag_v4.authorization_audit;
DROP POLICY IF EXISTS evaluation_scope ON bauer_rag_v4.evaluation_runs;
DROP POLICY IF EXISTS review_scope ON bauer_rag_v4.review_attestations;

DROP FUNCTION IF EXISTS bauer_rag_v4.resolve_pinned_release();
DROP FUNCTION IF EXISTS bauer_rag_v4.can_read_source(uuid);
DROP FUNCTION IF EXISTS bauer_rag_v4.readable_source_ids();
DROP FUNCTION IF EXISTS bauer_rag_v4.requested_source_ids();

DROP OWNED BY bauer_rag_v4_reader;
DROP OWNED BY bauer_rag_v4_worker;
DROP OWNED BY bauer_rag_v4_evaluator;
DROP OWNED BY bauer_rag_v4_reviewer;
DROP OWNED BY bauer_rag_v4_admin;
DROP ROLE bauer_rag_v4_reader;
DROP ROLE bauer_rag_v4_worker;
DROP ROLE bauer_rag_v4_evaluator;
DROP ROLE bauer_rag_v4_reviewer;
DROP ROLE bauer_rag_v4_admin;
